name: The Journal
favicon: null
layout_spectrum: 0.5018
typography_spectrum: 1
navigation:
  - name: About
    url: 'http://danielmrose.com'
    type: external
title: ''
description: A humble attempt at examining my life.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f21'
    - '#ffffff'
    - '#006940'
    - '#676566'
    - '#cecece'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
