typography_spectrum: 0.07950803279664626
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.051218936784137595
  lightness: 0.4066014244636097
  saturation: 0.8462354270917465
  rhythmicContrast: 0.7488456443806022
github: true
opengraph:
  image: null
  type: ''
  appId: ''
layout_spectrum: 0.3560508618371026
analytics:
  google: UA-12103272-1
  facebook: ''
  twitter: null
author:
  name: Daniel Rose
  email: drose@acts13.net
  url: 'http://danielmrose.com'
name: Daniel M. Rose
url: 'http://danielmrose.com'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    url: 'https://about.me/danielmrose'
    type: external
  - name: The Church
    url: 'http://theantiochmovement.org'
    type: external
  - name: Doubt On Tap
    url: 'http://facebook.com/doubtontap'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7172754f-5cec-4a8d-bb29-cd5250b1cf6e.ico
title: The Rev
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F73866566&url=https%3A%2F%2Fvimeo.com%2F73866566&image=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F448074590_1280.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=vimeo"
      width="1000" height="563" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Dan Rose
          url: 'https://vimeo.com/user1651728'
          avatar: {}
      related: []
      publisher:
        url: 'https://vimeo.com/'
        name: Vimeo
        favicon: 'https://f.vimeocdn.com/images_v6/favicon.ico'
        domain: vimeo.com
      keywords: []
      description: Just a snapshot for why we are launching the Antioch Movement.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vimeo://app.vimeo.com/videos/73866566'
          type: ios
          namespace: ai
          app_name: Vimeo
          app_store_id: '425194759'
        - should_fallback: 'true'
          app_name: Vimeo
          package: com.vimeo.android.videoapp
          url: 'vimeo://app.vimeo.com/videos/73866566'
          namespace: ai
          type: web
        - url: 'vimeo://app.vimeo.com/videos/73866566'
          namespace: twitter
          type: ipad
          name: Vimeo
          id: '425194759'
        - url: 'vimeo://app.vimeo.com/videos/73866566'
          namespace: twitter
          type: iphone
          name: Vimeo
          id: '425194759'
        - url: 'vimeo://app.vimeo.com/videos/73866566'
          namespace: twitter
          type: googleplay
          name: Vimeo
          id: com.vimeo.android.videoapp
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://vimeo.com/73866566'
      title: Antioch Promo
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Freshly tapped thoughts on life and God
purpose:
  - type: internal
    label: Subscribe!
    item: 31083efb-5c22-466c-b78f-b10e199615f3
  - type: contact
    url: 'mailto:drose@acts13.net'
    label: Contact Me
