typography_spectrum: 1
color:
  brandColors:
    - '#231f21'
    - '#ffffff'
    - '#006940'
    - '#676566'
    - '#cecece'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: The Journal
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Daniel M. Rose
description: A humble attempt at examining my life.
purpose: []
