typography_spectrum: 0.07950803279664626
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.051218936784137595
  lightness: 0.4066014244636097
  saturation: 0.8462354270917465
  rhythmicContrast: 0.7488456443806022
github: true
opengraph:
  image: null
  type: ''
  appId: ''
layout_spectrum: 0.3560508618371026
analytics:
  google: UA-12103272-1
  facebook: ''
  twitter: null
author:
  name: Daniel Rose
  email: drose@acts13.net
  url: 'http://danielmrose.com'
name: Daniel M. Rose
url: 'http://danielmrose.com'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    url: 'https://about.me/danielmrose'
    type: external
  - name: The Church
    url: 'http://theantiochmovement.org'
    type: external
  - name: Doubt On Tap
    url: 'http://facebook.com/doubtontap'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7172754f-5cec-4a8d-bb29-cd5250b1cf6e.ico
title: The Rev
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F4J9PkLboi6w%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D4J9PkLboi6w&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F4J9PkLboi6w%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Daniel M. Rose
          url: 'https://www.youtube.com/user/drose1976'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - duration
        - daniel
        - rose
        - views
        - antioch
        - libby
        - elementary
        - chopstick
        - creosote
        - '2016'
      description: A header video for my blog.
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=4J9PkLboi6w&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=4J9PkLboi6w&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=4J9PkLboi6w&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=4J9PkLboi6w&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=4J9PkLboi6w&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=4J9PkLboi6w'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=4J9PkLboi6w
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=4J9PkLboi6w
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/4J9PkLboi6w'
      title: The Rev
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Freshly tapped thoughts on life and God
purpose:
  - type: internal
    label: Subscribe!
    item: 31083efb-5c22-466c-b78f-b10e199615f3
  - type: contact
    url: 'mailto:drose@acts13.net'
    label: Contact Me
