typography_spectrum: 0.07800056256455287
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.05581461483483563
  lightness: 0.4034331274495488
  saturation: 0.848484150723342
  rhythmicContrast: 0.928468037632543
github: true
opengraph:
  image: null
  type: Article
  appId: '378960709007'
layout_spectrum: 0.9858757452787554
analytics:
  google: UA-12103272-1
  facebook: ''
  twitter: null
author:
  name: Daniel Rose
  email: drose@acts13.net
  url: 'http://danielmrose.com'
name: Daniel M. Rose
url: 'http://danielmrose.com'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    url: 'https://about.me/danielmrose'
    type: external
  - name: Doubt On Tap
    url: 'http://facebook.com/doubtontap'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7172754f-5cec-4a8d-bb29-cd5250b1cf6e.ico
title: The Rev
content: []
description: Freshly tapped thoughts on life and God
purpose:
  - type: internal
    label: Subscribe!
    item: 31083efb-5c22-466c-b78f-b10e199615f3
  - type: contact
    url: 'mailto:drose@acts13.net'
    label: Schedule Me To Speak
