typography_spectrum: 0.07950803279664626
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.051218936784137595
  lightness: 0.4066014244636097
  saturation: 0.8462354270917465
  rhythmicContrast: 0.7488456443806022
github: true
opengraph:
  image: null
  type: ''
  appId: ''
layout_spectrum: 0.3560508618371026
analytics:
  google: UA-12103272-1
  facebook: ''
  twitter: null
author:
  name: Daniel Rose
  email: drose@acts13.net
  url: 'http://danielmrose.com'
name: Daniel M. Rose
url: 'http://danielmrose.com'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    url: 'https://about.me/danielmrose'
    type: external
  - name: The Church
    url: 'http://theantiochmovement.org'
    type: external
  - name: Doubt On Tap
    url: 'http://facebook.com/doubtontap'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7172754f-5cec-4a8d-bb29-cd5250b1cf6e.ico
title: The Rev
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/91fff8d8-a88c-48d2-8f91-3f47f261f90b.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/91fff8d8-a88c-48d2-8f91-3f47f261f90b.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Freshly tapped thoughts on life and God
purpose:
  - type: internal
    label: Subscribe!
    item: 31083efb-5c22-466c-b78f-b10e199615f3
  - type: contact
    url: 'mailto:drose@acts13.net'
    label: Contact Me
